/**
 * Work content model (MCD-5, PRD §10, §26, §27).
 *
 * A case study is content, not code: two Markdown files — one per locale —
 * under `src/content/work/`. This module owns the two rules that make that
 * work:
 *
 * - `workEntrySchema`, the required metadata every entry must carry. The
 *   content collection validates against it, so a malformed entry fails the
 *   build with the file and field named.
 * - `assertWorkContentIsConsistent`, the invariants a *pair* of entries must
 *   satisfy. A schema can only see one file at a time; these are what keep
 *   `/work/<slug>/` and `/zh/work/<slug>/` resolvable from each other.
 *
 * Deliberately free of `astro:content` imports. Everything here is plain data
 * plus zod, so the rules are unit-testable without the content layer.
 */

import { z } from 'astro/zod';

import { LOCALES, type Locale } from '../i18n/locales';

/** Lowercase words joined by single hyphens — the URL segment form. */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const SLUG_MESSAGE = 'must be lowercase words joined by single hyphens, e.g. "ai-coding-skills"';

/**
 * Required metadata for one localized Work entry.
 *
 * Strict on purpose: an unknown key is almost always a misspelled required one
 * (`translationkey`), and reporting both the stray key and the missing field
 * points at the mistake instead of the symptom.
 */
export const workEntrySchema = z.strictObject({
  /** Localized case-study title. Also the `<title>` and `og:title` stem. */
  title: z.string().min(1),
  /** Localized category line, e.g. `Product · AI Systems` (PRD §10). */
  type: z.string().min(1),
  /** Localized one-line summary. Drives the index card and the description. */
  summary: z.string().min(1),
  /** URL segment: `/work/<slug>/` and `/zh/work/<slug>/`. */
  slug: z.string().regex(SLUG_PATTERN, `slug ${SLUG_MESSAGE}`),
  /** Which localized file this is. Must match the directory it lives in. */
  locale: z.enum(LOCALES),
  /**
   * Locale-independent identity shared by every translation of one case study
   * (PRD §27). The pairing is by this key, not by filename.
   */
  translationKey: z.string().regex(SLUG_PATTERN, `translationKey ${SLUG_MESSAGE}`),
  /** Index position, ascending. PRD §10 lists Shouri before AI Coding Skills. */
  order: z.number().int().nonnegative(),
  /** Withheld from the index and from route generation while `true`. */
  draft: z.boolean().default(false),
});

export type WorkEntryData = z.infer<typeof workEntrySchema>;

/**
 * The shape this module needs from a content-collection entry.
 *
 * `CollectionEntry<'work'>` satisfies it structurally, so pages can pass
 * `getCollection('work')` straight through.
 */
export interface WorkEntry {
  /** `<locale>/<slug>`, as generated by the collection loader. */
  id: string;
  data: WorkEntryData;
}

function fail(message: string): never {
  throw new Error(`Work content: ${message}`);
}

/** File path an entry's own metadata says it should live at. */
function expectedPath(data: WorkEntryData): string {
  return `src/content/work/${data.locale}/${data.slug}.md`;
}

/**
 * Verify every cross-file invariant the Work model depends on.
 *
 * Throws at build time — during `getStaticPaths` and index rendering — with the
 * offending entry id and field in the message.
 *
 * The invariants, and why each one exists:
 *
 * 1. An entry's id matches its own `locale` and `slug`. Catches a file dropped
 *    into the wrong locale directory or renamed without updating frontmatter.
 * 2. `slug` and `translationKey` map one-to-one. The language switch rewrites
 *    only the locale prefix (`src/lib/i18n.ts`), so translations of one case
 *    study must share a slug or the switch would land on a 404.
 * 3. Every translation key exists in every locale. PRD §7 requires Traditional
 *    Chinese to be a complete localized experience, not a partial one.
 * 4. `order` and `draft` agree across locales. Otherwise the two indexes would
 *    disagree on what exists, or in what sequence.
 */
export function assertWorkContentIsConsistent(entries: readonly WorkEntry[]): void {
  // Sort first so the *same* broken content always reports the same error,
  // whatever order the loader happened to hand entries over in.
  const ordered = [...entries].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

  const keyBySlug = new Map<string, string>();
  const slugByKey = new Map<string, string>();
  const byTranslationKey = new Map<string, WorkEntry[]>();

  for (const entry of ordered) {
    const { locale, slug, translationKey } = entry.data;

    if (entry.id !== `${locale}/${slug}`) {
      fail(
        `entry "${entry.id}" declares locale "${locale}" and slug "${slug}", ` +
          `so it must be the file ${expectedPath(entry.data)}`,
      );
    }

    const knownKey = keyBySlug.get(slug);
    if (knownKey !== undefined && knownKey !== translationKey) {
      fail(
        `slug "${slug}" is used by translationKey "${knownKey}" and "${translationKey}"; ` +
          `one slug belongs to exactly one case study (see ${expectedPath(entry.data)})`,
      );
    }
    keyBySlug.set(slug, translationKey);

    const knownSlug = slugByKey.get(translationKey);
    if (knownSlug !== undefined && knownSlug !== slug) {
      fail(
        `translationKey "${translationKey}" maps to slug "${knownSlug}" and "${slug}"; ` +
          `every translation of a case study must share one slug so the language ` +
          `switch resolves (see ${expectedPath(entry.data)})`,
      );
    }
    slugByKey.set(translationKey, slug);

    const group = byTranslationKey.get(translationKey);
    if (group) group.push(entry);
    else byTranslationKey.set(translationKey, [entry]);
  }

  for (const [translationKey, group] of byTranslationKey) {
    const missing = LOCALES.filter((locale) => !group.some((e) => e.data.locale === locale));
    if (missing.length > 0) {
      const slug = slugByKey.get(translationKey);
      fail(
        `translationKey "${translationKey}" has no ${missing.join(', ')} entry; ` +
          `add ${missing.map((locale) => `src/content/work/${locale}/${slug}.md`).join(' and ')}`,
      );
    }

    // Safe: `missing.length === 0` means every locale is present, so is the first.
    const reference = group[0]!;
    for (const entry of group) {
      for (const field of ['order', 'draft'] as const) {
        if (entry.data[field] !== reference.data[field]) {
          fail(
            `translationKey "${translationKey}" disagrees on "${field}": ` +
              `"${reference.id}" has ${String(reference.data[field])} but ` +
              `"${entry.id}" has ${String(entry.data[field])}`,
          );
        }
      }
    }
  }
}

/**
 * Published entries for one locale, in index order.
 *
 * Validates the whole collection first — a broken pair on any entry is a
 * problem for both indexes, not only the locale being rendered.
 *
 * Generic over the entry type so a `CollectionEntry<'work'>` survives the
 * filter and can still be handed to `render()`.
 */
export function workEntriesForLocale<T extends WorkEntry>(
  entries: readonly T[],
  locale: Locale,
): T[] {
  assertWorkContentIsConsistent(entries);

  return entries
    .filter((entry) => entry.data.locale === locale && !entry.data.draft)
    .sort(
      (a, b) =>
        a.data.order - b.data.order ||
        // Byte-order tie-break rather than `localeCompare`, so the build is
        // reproducible regardless of the host's ICU data.
        (a.data.slug < b.data.slug ? -1 : a.data.slug > b.data.slug ? 1 : 0),
    );
}
